apiVersion: v1
kind: Service
metadata:
  name: boardgame-service
  namespace: production
spec:
  type: LoadBalancer
  selector:
    app: boardgame
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP